include: package:very_good_analysis/analysis_options.4.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude: [lib/app/http_client/http_client.dart, lib/image_finder/data/datasources/image_datasource.dart, lib/image_finder/domain/repositories/image_repository.dart]